### PR TITLE
copy state on `start!` for local manager

### LINKED ISSUE #25: start! mutates init_state when batch_manager is root process
MWEs based off the `labeled_signals` generated by the test data.

### Example 1: batch_manager == root && batch_workers !== root

```julia
julia> batches = RandomBatches(labeled_signals, nothing, nothing, 1, 3, Second(60))

julia> addprocs(3);

julia> @everywhere begin
           using Pkg
           Pkg.activate(@__DIR__)
           using OndaBatches
       end
      From worker 2:      Activating project at `~/.julia/dev/OndaBatches`

julia> batcher = Batcher(1, [2], batches; start=false);

julia> init_state = MersenneTwister(1)
MersenneTwister(1)

julia> start!(batcher, init_state);

julia> init_state  # NOTE: start! mutated init_state
MersenneTwister(1, (0, 2256, 0, 36, 1002, 36))

julia> take!(batcher, init_state)
┌ Warning: mismatch between requested batch state and Batcher state, restarting
│   state = MersenneTwister(1, (0, 2256, 0, 12, 1002, 12))
│   prev_state = MersenneTwister(1)
└ @ OndaBatches ~/.julia/dev/OndaBatches/src/batch_services.jl:547
[ Info: stopping batcher
[ Info: batch channel closed, stopping batching
[ Info: channel close, stopping
┌ Warning: only one extra worker to load batches!
└ @ OndaBatches ~/.julia/dev/OndaBatches/src/batch_services.jl:419
[ Info: starting multi-worker batching, with manager 1 and workers WorkerPool(Channel{Int64}(9223372036854775807), Set([2]), RemoteChannel{Channel{Any}}(1, 1, 5)), at state MersenneTwister(1, (0, 2256, 0, 18, 1002, 18))
(([-3.75 -5.0 … -5.5 -11.75;;; -21.75 -18.0 … 14.5 7.25;;; -3.7155719473958015 -6.1875334940850735 … 12.748912675306201 11.78759429603815], [0x01 0x01;;; 0x01 0x01;;; 0x03 0x03]), MersenneTwister(1, (0, 2256, 0, 24, 1002, 24)))

julia> Unhandled Task ERROR: no process with id 0 exists
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] worker_from_id(pg::Distributed.ProcessGroup, i::Int64)
   @ Distributed ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/cluster.jl:1097
 [3] worker_from_id
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/cluster.jl:1089 [inlined]
 [4] #remotecall_fetch#162
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492 [inlined]
 [5] remotecall_fetch
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492 [inlined]
 [6] call_on_owner
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:565 [inlined]
 [7] isopen
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:769 [inlined]
 [8] macro expansion
   @ ~/.julia/dev/OndaBatches/src/batch_services.jl:171 [inlined]
 [9] (::OndaBatches.var"#44#48"{RemoteChannel{Channel{Any}}, Channel{OndaBatches.BatchJob}})()
   @ OndaBatches ./task.jl:484
julia> 
```

Note that the above works if we refresh `init_state`
```julia
julia> take!(batcher, MersenneTwister(1))
(([-4.0 -2.25 … -8.75 -6.75;;; 8.25 4.25 … 4.0 4.75;;; 33.508812077343464 28.44281680881977 … -7.14122224599123 -13.36690317839384], [0x01 0x01;;; 0x01 0x01;;; 0x01 0x01]), MersenneTwister(1, (0, 2256, 0, 6, 1002, 6)))
```

### Example 2: batch_manager == root && batch_worker == root

Same as above:

```julia
julia> batcher = Batcher(1, [1], batches; start=false);

julia> init_state = MersenneTwister(1)
MersenneTwister(1)

julia> start!(batcher, init_state);
┌ Warning: only one extra worker to load batches!
└ @ OndaBatches ~/.julia/dev/OndaBatches/src/batch_services.jl:419
[ Info: starting multi-worker batching, with manager 2 and workers WorkerPool(Channel{Int64}(9223372036854775807), Set([2]), RemoteChannel{Channel{Any}}(1, 1, 123)), at state MersenneTwister(1)

julia> init_state
MersenneTwister(1)

julia> take!(batcher, init_state)
┌ Warning: mismatch between requested batch state and Batcher state, restarting
│   state = MersenneTwister(1, (0, 2256, 0, 36, 1002, 36))
│   prev_state = MersenneTwister(1)
└ @ OndaBatches ~/.julia/dev/OndaBatches/src/batch_services.jl:547
[ Info: stopping batcher
[ Info: batch channel closed, stopping batching
┌ Warning: only one extra worker to load batches!
└ @ OndaBatches ~/.julia/dev/OndaBatches/src/batch_services.jl:419
[ Info: starting multi-worker batching, with manager 1 and workers WorkerPool(Channel{Int64}(9223372036854775807), Set([1]), RemoteChannel{Channel{Any}}(1, 1, 14)), at state MersenneTwister(1, (0, 2256, 0, 36, 1002, 36))
(([35.03471426665783 33.386739902198315 … -5.981536582112312 -11.169604025781155;;; -159.75 312.0 … 165.5 -232.75;;; -47.549019515514374 16.17647075653076 … -1.4705880880355835 -99.50980389118195], [0x03 0x02;;; 0x04 0x04;;; 0x01 0x01]), MersenneTwister(1, (0, 2256, 0, 42, 1002, 42)))

julia> Unhandled Task ERROR: no process with id 0 exists
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] worker_from_id(pg::Distributed.ProcessGroup, i::Int64)
   @ Distributed ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/cluster.jl:1097
 [3] worker_from_id
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/cluster.jl:1089 [inlined]
 [4] #remotecall_fetch#162
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492 [inlined]
 [5] remotecall_fetch
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:492 [inlined]
 [6] call_on_owner
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:565 [inlined]
 [7] isopen
   @ ~/.julia-downloads/julia-1.8.2/share/julia/stdlib/v1.8/Distributed/src/remotecall.jl:769 [inlined]
 [8] macro expansion
   @ ~/.julia/dev/OndaBatches/src/batch_services.jl:171 [inlined]
 [9] (::OndaBatches.var"#44#48"{RemoteChannel{Channel{Any}}, Channel{OndaBatches.BatchJob}})()
   @ OndaBatches ./task.jl:484
```

---

### Works if batch_manager !== root && batch_worker ! == root

```julia
julia> batcher = Batcher(2, [3, 4], batches; start=false);

julia> init_state = MersenneTwister(1)
MersenneTwister(1)

julia> start!(batcher, init_state);

julia> init_state  # remains unchanged
MersenneTwister(1)

julia> take!(batcher, init_state)
(([-4.0 -2.25 … -8.75 -6.75;;; 8.25 4.25 … 4.0 4.75;;; 33.508812077343464 28.44281680881977 … -7.14122224599123 -13.36690317839384], [0x01 0x01;;; 0x01 0x01;;; 0x01 0x01]), MersenneTwister(1, (0, 2256, 0, 6, 1002, 6)))
```

### Works if batch_manager != root && batch_worker == root

Finally, for completeness it also works if we flip the manager and worker around:
```julia
julia> batcher = Batcher(2, [1], batches; start=false);

julia> init_state = MersenneTwister(1);

julia> start!(batcher, init_state);
┌ Warning: only one extra worker to load batches!
└ @ OndaBatches ~/.julia/dev/OndaBatches/src/batch_services.jl:419
[ Info: starting multi-worker batching, with manager 2 and workers WorkerPool(Channel{Int64}(9223372036854775807), Set([2]), RemoteChannel{Channel{Any}}(1, 1, 135)), at state MersenneTwister(1)

julia> take!(batcher, init_state)
(([-4.0 -2.25 … -8.75 -6.75;;; 8.25 4.25 … 4.0 4.75;;; 33.508812077343464 28.44281680881977 … -7.14122224599123 -13.36690317839384], [0x01 0x01;;; 0x01 0x01;;; 0x01 0x01]), MersenneTwister(1, (0, 2256, 0, 6, 1002, 6)))
```

### PR DESCRIPTION
**Pull request by kleinschmidt**
This adds a small check in `start!` that will copy the initial state if the manager PID is the same as the calling worker.  This fixes #25 (and also adds tests to make sure we can reproduce that behavior)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204515777435058

### CODE REVIEW

**Review by glennmoy — APPROVED** [review]

File: test/batch_services.jl [hunk 1]
```diff
@@ -101,6 +101,25 @@ unwrap(e::CapturedException) = unwrap(e.ex)
...
+
+            x1, s1 = take!(b1, init_state)
+            x2, s2 = take!(b2, init_state)
+
+            @test x1 == x2
+            @test s1 == s2 != init_state
+
+            # not mutated
+            @test init_state == StableRNG(1)
+        end
```
Comment (glennmoy) [inline test/batch_services.jl:121]: do we need to `stop!` the batcher or anything?

Comment (kleinschmidt) [reply test/batch_services.jl:121]: whoops, yeah maybe.  shouldn't be a huge issue though these batches are small by design...

Comment (glennmoy) [reply test/batch_services.jl:121]: what happens if we don't? is there just a bunch of unallocated memory hanging around?

Comment (kleinschmidt) [reply test/batch_services.jl:121]: yeah they get cleaned up when the suite finishes.  dangling tasks are generally frowned upon but in tests it's not the end of the world...
